### ISSUE TITLE
Question: How to import a civilization

### ISSUE THREAD

**Issue by volkerkarle** [Krakenmeister/AoE2-Civbuilder#1]
Hi Krakenmeister,

Thanks first for your amazing work. This is a great idea and I am eager to try this draft mode soon with some friends.

One question: Let's assume I created my own custom civilization and saved the .json file, how do I use it now in the game? I figured I somehow have to use the platform https://www.ageofempires.com/mods/ but I do not see how exactly.

Best,

v.

**Comment by Krakenmeister** [comment]
Hello!

If you create custom civilizations using the builder, you have to go to "Combine Civilizations" to turn the .json file(s) into a mod.zip file. Then there is a data.zip and a ui.zip file inside to publish on ageofempires.com. There is also a guide on how to do this in the Help section on the website page.

Have fun!

**Comment by volkerkarle** [comment]
Thanks!
