### ISSUE TITLE
Houses are missing

### ISSUE THREAD

**Issue by Jsennin1** [Krakenmeister/AoE2-Civbuilder#5]
Hello , i tried to combine 2 civs to play with my friend, however when we combine them houses are missing at dark age. we even tried in single player to check , same problem. Incase you want to check our files, I will attach json files. Thanks
[combined civs.zip](https://github.com/Krakenmeister/AoE2-Civbuilder/files/7841879/combined.civs.zip)

**Comment by Krakenmeister** [comment]
That was an issue with the update this morning, but is now fixed! Thanks for reporting, if you combine your .json files again it should work now.
